public class QuestionBank {
    Question[] question = {
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
        new Question(null, null, 0),
    };


}
